### ISSUE TITLE
`pos` attributes are not `int` but `float32`

### ISSUE THREAD

**Issue by jeromenerf** [VojtechVitek/go-trello#28]
For all entities, the `pos` attributes should be set to float32 since trello sometimes set it to something like "pos: 43007.890625,", causing json unmarshal to panic.

```
panic: json: cannot unmarshal number 36863.90625 into Go value of type int
```

**Comment by jeromenerf** [comment]
The API changed a few hours ago, so I contacted Trello to verify if this is a bug or a feature and will update this issue accordingly.

**Comment by fiatjaf** [comment]
In fact it was stupid to change the attribute to `int` from `float32`. I can say that because I was the author of the change. For posting data into Trello strings (`"top"`, `"bottom"`) are also accepted, so we should probably use `interface{}` in the structs.

**Comment by jeromenerf** [comment]
Oh, good catch, I remember that this API is sometimes a bit inconsistent, returning whether nil, null or [] for empty collection attributes among other niceties.

I'll keep you posted of trello's answer.

**Comment by VojtechVitek** [comment]
Thanks for investigating this!

**Comment by jeromenerf** [comment]
OK, so Trello `pos` are and have always have been floats but most of the time, these attributes returns without decimal points. This is a feature.

Apparently, `pos` values such as those described only happen when frequent changes are applied in a list, checklist...

As a consequence, we should probably follow @fiatjaf idea and use the `interface{}` type.

**Comment by VojtechVitek** [comment]
let's use float32

**Comment by jeromenerf** [comment]
Actually, we need to use string when POSTing a newly created positionable
resource.

**Comment by mehdy** [comment]
for `top` and `bottom` we can use -1 and -2  for example since trello doesn't use negatives

**Comment by eparis** [comment]
my version of a fix for this was just merged!

**Comment by VojtechVitek** [comment]
I think this can be closed now.

If we ever need to parse "top" and "bottom", we might use custom Unmarshaller with `math.MaxFloat64` and `-math.MaxFloat64`
